---

- name: Creates directory
  file:
    path: /home/ubuntu/backend-artifact
    state: directory

- name: "Unarchive"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend-artifact

- name: "npm install"
  shell: |
    cd /home/ubuntu/backend-artifact
    npm i
    
- name: "Executing Node app with PM2"
  shell: |
    cd /home/ubuntu/backend-artifact/dist
    pm2 stop default
    pm2 start main.js
 
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

